//! Behavioural tests for the FastCDC chunker.
//!
//! The 2016 paper publishes no chunk-boundary vectors (the GEAR table values
//! were never in it), so the pinned vector is generated: `GOLDEN_BOUNDARIES`
//! was produced by this implementation and pinned so every future change is
//! a deliberate, reviewed diff. Everything else is a structural property the
//! paper itself claims: determinism, `[min, max]` chunk sizes, insertion
//! locality, duplicate-block boundary reuse, and the normalized
//! distribution.

use pith_cdc::{
    BUZHASH_WINDOW, Buzhash64, Chunk, FastCdc, GEAR, MAXIMUM_MAX, Normalization, chunk,
};

use pith_digest::{Error, SplitMix64};

const MIN: usize = 2048;
const AVG: usize = 8192;
const MAX: usize = 32768;

/// Deterministic pseudo-random bytes from `SplitMix64` (no `rand` allowed).
fn stream(seed: u64, len: usize) -> Vec<u8> {
    let mut rng = SplitMix64::new(seed);
    let mut out = vec![0u8; len];
    rng.fill_bytes(&mut out);
    out
}

/// End-offsets of every chunk — the cut positions of the stream.
fn boundaries(chunks: &[Chunk]) -> Vec<usize> {
    chunks.iter().map(|c| c.offset + c.length).collect()
}

#[test]
fn boundaries_are_deterministic_across_calls() {
    let data = stream(0xdead_beef, 1 << 20);
    let a: Vec<Chunk> = FastCdc::new(&data, MIN, AVG, MAX).unwrap().collect();
    let b: Vec<Chunk> = FastCdc::new(&data, MIN, AVG, MAX).unwrap().collect();
    assert_eq!(a, b);
    assert!(!a.is_empty());
}

#[test]
fn boundaries_are_deterministic_across_runs_pinned() {
    // One fixed known-answer: the exact boundary list for this fixed 1 MiB
    // stream at (2 KiB, 8 KiB, 32 KiB, level 2). Generated by this crate and
    // pinned; the paper ships no vectors to compare against. Any change here
    // is a deliberate, reviewable behaviour change.
    let data = stream(0x5eed_5eed_5eed_5eed, 1 << 20);
    let chunks: Vec<Chunk> = FastCdc::new(&data, MIN, AVG, MAX).unwrap().collect();
    assert_eq!(boundaries(&chunks), GOLDEN_BOUNDARIES);
}

#[test]
fn chunks_tile_the_input_and_respect_min_max() {
    for seed in [1u64, 0xabab_abab, u64::MAX] {
        let data = stream(seed, 300_000);
        let chunks: Vec<Chunk> = FastCdc::new(&data, MIN, AVG, MAX).unwrap().collect();
        let total: usize = chunks.iter().map(|c| c.length).sum();
        assert_eq!(total, data.len());
        assert_eq!(chunks.first().unwrap().offset, 0);
        assert_eq!(
            chunks.last().unwrap().offset + chunks.last().unwrap().length,
            data.len()
        );
        for w in chunks.windows(2) {
            assert_eq!(w[0].offset + w[0].length, w[1].offset);
            // Every chunk except the last must be within [min, max]; the
            // last is the remainder and may be shorter than min.
            assert!(
                (MIN..=MAX).contains(&w[0].length),
                "bad len {}",
                w[0].length
            );
        }
    }
}

#[test]
fn chunk_fn_matches_iterator() {
    let data = stream(0x0bad_f00d, 200_000);
    let pairs = chunk(&data, MIN, AVG, MAX).unwrap();
    let iter: Vec<(usize, usize)> = FastCdc::new(&data, MIN, AVG, MAX)
        .unwrap()
        .map(|c| (c.offset, c.length))
        .collect();
    assert_eq!(pairs, iter);
}

#[test]
fn one_byte_insertion_changes_only_the_boundary_region() {
    // Insertion locality: inserting one byte at position x must not move any
    // boundary more than one window (64 bytes) before x. Within a chunk a
    // boundary's fingerprint depends only on local content, so pre-insertion
    // boundaries strictly more than one window before x must survive
    // verbatim; post-insertion the stream resynchronizes because the +1
    // shift affects windows equally on both sides.
    let original = stream(0x1234_5678, 1 << 18);
    let x = 1 << 16;
    let mut edited = original.clone();
    edited.insert(x, 0x5a);

    let a: Vec<Chunk> = FastCdc::new(&original, MIN, AVG, MAX).unwrap().collect();
    let b: Vec<Chunk> = FastCdc::new(&edited, MIN, AVG, MAX).unwrap().collect();
    let bounds_a = boundaries(&a);
    let bounds_b = boundaries(&b);

    // Boundaries comfortably before the insertion are untouched.
    let safe: Vec<usize> = bounds_a
        .iter()
        .copied()
        .filter(|&b| b + BUZHASH_WINDOW < x)
        .collect();
    for &bnd in &safe {
        assert!(
            bounds_b.contains(&bnd),
            "boundary {bnd} vanished after a distant insert"
        );
    }

    // The streams must resynchronize: a cut after the insert is a cut of the
    // same content shifted one byte later, so a boundary at `b` in the
    // original reappears at `b + 1` in the edited stream.
    let resynced = bounds_a
        .iter()
        .any(|&bnd| bnd > x + BUZHASH_WINDOW && bounds_b.contains(&(bnd + 1)));
    assert!(
        resynced,
        "chunker never resynchronized after a 1-byte insert"
    );
}
#[test]
fn duplicated_block_refinds_the_same_boundary() {
    // Dedup property: copying a 4 KiB block ahead of the stream re-declares
    // the same cut inside the copy — boundaries are content-defined, not
    // position-defined.
    //
    // Model that makes this exact rather than probabilistic: the gear
    // fingerprint at candidate index `i` is the fold of `data[min ..= i]`,
    // i.e. its effective window is the last 64 bytes of that span. Take a
    // cut `b` in the original and copy `B = data[b-4032 .. b+64]` (4 KiB
    // containing `b` at offset 4032). After `C = B ++ data`:
    //
    // * candidate `j = 4032` in C sees `C[3969..=4032] == data[b-63 ..= b]`,
    //   the exact window that fired at `b`, and the mask is identical at
    //   level 0 — so C *must* cut at 4032;
    // * candidates `j` in `[min, 4032)` see `data[b-4032+j-63 ..= b-4032+j]`
    //   once `j >= min + 63`, windows that were already candidates in the
    //   original scan inside chunk [prev, b) and did not fire; the first
    //   `63` candidates see shorter windows — the fingerprint fold from an
    //   empty start — and empirically do not fire on this stream either
    //   (verified: shift is always found).
    //
    // So the first boundary of C is exactly 4032, inside the copy region.
    let data = stream(0x7777_aaaa, 1 << 18);
    let bounds = boundaries(
        &FastCdc::with_level(&data, MIN, AVG, MAX, Normalization::Level0)
            .unwrap()
            .collect::<Vec<_>>(),
    );

    // Pick a cut far enough past the previous boundary that all of B's
    // candidate windows existed in the original scan: need b - prev >= 4032.
    let mut chosen = None;
    let mut prev = 0usize;
    for &b in &bounds {
        if prev > 0 && b - prev >= 4096 && b + 64 < data.len() {
            chosen = Some(b);
            break;
        }
        prev = b;
    }
    let b = chosen.expect("test data must contain a qualifying boundary");

    let mut shifted = Vec::with_capacity(4096 + data.len());
    shifted.extend_from_slice(&data[b - 4032..b + 64]);
    shifted.extend_from_slice(&data);

    let shifted_bounds = boundaries(
        &FastCdc::with_level(&shifted, MIN, AVG, MAX, Normalization::Level0)
            .unwrap()
            .collect::<Vec<_>>(),
    );
    assert_eq!(
        shifted_bounds.first().copied(),
        Some(4032),
        "copied block must re-declare its own boundary first: {shifted_bounds:?}"
    );
}

#[test]
fn avg_plus_minus_20pct_keeps_chunk_count_close() {
    // Spec §5 property: chunk count stays stable when `avg` moves ±20%.
    // Count scales roughly inversely with avg, so a ±20% avg change moves
    // the count by ~∓17%/+25%; we assert the looser sanity band and that the
    // change is real (not identical), proving the parameter is wired in.
    let data = stream(0xcafe_f00d, 1 << 20);
    let n = |avg: usize| FastCdc::new(&data, MIN, avg, MAX).unwrap().count();
    let base = n(AVG);
    let low = n(6554); // ~avg * 0.8
    let high = n(9830); // ~avg * 1.2
    assert!(
        low > base,
        "smaller avg must yield more chunks: {low} !> {base}"
    );
    assert!(
        high < base,
        "larger avg must yield fewer chunks: {high} !< {base}"
    );
    assert!(low as f64 <= base as f64 * 1.35);
    assert!(high as f64 >= base as f64 * 0.70);
}

#[test]
fn normalization_level_3_tightens_the_distribution() {
    // Paper figure 9: level 3 concentrates chunks near the average. Assert
    // the population stddev falls, which fails if normalization is wired
    // backwards (strict/loose swapped) — the sign error is observable here.
    let data = stream(0x2468_ace0, 1 << 20);
    let lens = |level: Normalization| {
        FastCdc::with_level(&data, MIN, AVG, MAX, level)
            .unwrap()
            .map(|c| c.length as f64)
            .collect::<Vec<_>>()
    };
    let stddev = |v: &[f64]| {
        let mean = v.iter().sum::<f64>() / v.len() as f64;
        (v.iter().map(|x| (x - mean).powi(2)).sum::<f64>() / v.len() as f64).sqrt()
    };
    let l0 = stddev(&lens(Normalization::Level0));
    let l3 = stddev(&lens(Normalization::Level3));
    assert!(
        l3 < l0 * 0.8,
        "level3 stddev {l3} not tighter than level0 {l0}"
    );
}

#[test]
fn chunk_smaller_than_min_is_returned_whole() {
    let tiny = stream(9, 1024);
    let chunks: Vec<Chunk> = FastCdc::new(&tiny, MIN, AVG, MAX).unwrap().collect();
    assert_eq!(chunks.len(), 1);
    assert_eq!(chunks[0].length, 1024);
    assert_eq!(chunks[0].hash, 0); // sub-minimum chunks are never hash-judged
}

#[test]
fn empty_input_yields_no_chunks() {
    assert_eq!(
        chunk(&[], MIN, AVG, MAX).unwrap(),
        Vec::<(usize, usize)>::new()
    );
}

#[test]
fn invalid_params_are_named_errors() {
    let data = stream(1, 1 << 12);
    let err = |min, avg, max| FastCdc::new(&data, min, avg, max).expect_err("must reject");
    // Each rejected combination must be BadValue naming the field.
    for e in [
        err(8, AVG, MAX),               // min below the 64-byte floor
        err(MIN, AVG, MAXIMUM_MAX + 1), // max above the 16 MiB ceiling
        err(AVG, MIN, MAX),             // min > avg
        err(MIN, MAX, AVG),             // avg > max
    ] {
        assert!(
            matches!(e, Error::BadValue(_)),
            "wrong error variant: {e:?}"
        );
    }
}

#[test]
fn gear_fingerprint_matches_the_roll_up() {
    // The chunk's recorded `hash` must equal the Gear fingerprint folded
    // over `data[min ..= cut]` — the property downstream users (RapidCDC
    // hints) rely on.
    let data = stream(0xfeed_beef, 1 << 17);
    let chunks: Vec<Chunk> = FastCdc::new(&data, MIN, AVG, MAX).unwrap().collect();
    let c = chunks[0];
    let mut fp = 0u64;
    for i in c.offset + MIN..=c.offset + c.length {
        fp = fp.wrapping_shl(1).wrapping_add(GEAR[data[i] as usize]);
    }
    assert_eq!(fp, c.hash);
}

#[test]
fn buzhash_window_rolls_and_evicts() {
    // After 64 pushes the rolling state must equal a from-scratch fold of
    // exactly the last 64 bytes — the defining property of the window.
    let data = stream(0x1357_9bdf, 10_000);
    let mut h = Buzhash64::new();
    for (i, &b) in data.iter().enumerate() {
        h.push(b);
        if i >= BUZHASH_WINDOW - 1 {
            let mut want = 0u64;
            for &w in &data[i + 1 - BUZHASH_WINDOW..=i] {
                want = want.rotate_left(1) ^ GEAR[w as usize];
            }
            assert_eq!(h.fingerprint(), want, "window diverged at byte {i}");
        }
    }
}

#[test]
fn buzhash_window_shifts_with_content() {
    // The same 64 bytes at a different position hash identically, and a
    // one-byte difference anywhere in the window changes the fingerprint.
    let a = stream(0xaaaa_5555, 64);
    let mut b = a.clone();
    b[63] ^= 1;
    let h = |w: &[u8]| {
        let mut h = Buzhash64::new();
        h.update(w);
        h.fingerprint()
    };
    assert_eq!(h(&a), h(&a));
    assert_ne!(h(&a), h(&b));
    let mut h1 = Buzhash64::new();
    h1.update(&[0u8; 8]); // warm-up bytes that then slide out
    h1.update(&a);
    let mut h2 = Buzhash64::new();
    h2.update(&a);
    assert_eq!(h1.fingerprint(), h2.fingerprint());
}

/// Golden boundary list: this crate's own output on
/// `stream(0x5eed5eed5eed5eed, 1 MiB)` at (2048, 8192, 32768, Level2),
/// pinned so a behaviour change is a loud, reviewable diff.
#[rustfmt::skip]
const GOLDEN_BOUNDARIES: &[usize] = &[
    2386, 17044, 26124, 38661, 47315, 59688, 67914, 79612,
    88462, 97957, 108660, 120052, 128304, 140189, 153506, 164672,
    166778, 178007, 180638, 187170, 196794, 205241, 214760, 225548,
    236225, 248292, 256849, 265593, 279412, 287874, 298459, 308980,
    322361, 334729, 345365, 353934, 364029, 373828, 382106, 390947,
    394761, 403450, 413816, 424423, 433677, 443002, 453158, 461996,
    472883, 476978, 485608, 497067, 505506, 515078, 521402, 530547,
    541361, 552967, 562377, 576266, 590279, 598698, 607685, 617094,
    631368, 639899, 648873, 658617, 667579, 682374, 691420, 700165,
    706608, 721701, 731973, 746161, 754366, 769609, 777949, 781400,
    790457, 802152, 813089, 823158, 835004, 846185, 857580, 866262,
    876849, 889308, 897690, 909627, 920124, 931769, 940242, 942586,
    954121, 966079, 975406, 988418, 997756, 1005584, 1016876, 1027080,
    1038859, 1047070, 1048576,];
