//! Conformance test: replays the committed reference chunking vectors.
//!
//! `tests/reference.json` is generated by `tools/gen-reference` from a fixed
//! input corpus (SplitMix64 streams, degenerate fills, a sawtooth pattern)
//! chunked across a matrix of `(min, avg, max, level)` parameters. This test
//! rebuilds every input from the same recipe, re-chunks it, and requires the
//! exact `(offset, length, fingerprint)` triples back — plus the tiling
//! invariant (`chunks` cover the input exactly) for every vector.
//!
//! The JSON is read with a tiny parser for the strict subset the generator
//! emits (objects, arrays, plain strings, unsigned integers): the suite has
//! no third-party dependencies, so there is no serde to reach for.

use pith_cdc::{Chunk, FastCdc, Normalization};
use pith_digest::SplitMix64;

/// The committed vector document, embedded at compile time.
const REFERENCE_JSON: &str = include_str!("reference.json");

// ---------------------------------------------------------------------------
// Minimal JSON subset parser
// ---------------------------------------------------------------------------

/// A parsed JSON value: only what the generator emits.
#[derive(Debug, Clone, PartialEq)]
enum Json {
    /// `{ "key": value, ... }`, insertion order preserved.
    Obj(Vec<(String, Json)>),
    /// `[value, ...]`.
    Arr(Vec<Json>),
    /// A string without escape sequences (the generator emits none).
    Str(String),
    /// A non-negative integer literal.
    Num(u64),
}

impl Json {
    /// Object member lookup; panics with the missing key named.
    fn get(&self, key: &str) -> &Json {
        match self {
            Json::Obj(members) => members
                .iter()
                .find(|(k, _)| k == key)
                .map(|(_, v)| v)
                .unwrap_or_else(|| panic!("reference.json: missing key {key:?}")),
            other => panic!("reference.json: expected object for key {key:?}, got {other:?}"),
        }
    }

    /// String value.
    fn as_str(&self) -> &str {
        match self {
            Json::Str(s) => s,
            other => panic!("reference.json: expected string, got {other:?}"),
        }
    }

    /// Unsigned integer value.
    fn as_num(&self) -> u64 {
        match self {
            Json::Num(n) => *n,
            other => panic!("reference.json: expected number, got {other:?}"),
        }
    }

    /// Array value.
    fn as_arr(&self) -> &[Json] {
        match self {
            Json::Arr(items) => items,
            other => panic!("reference.json: expected array, got {other:?}"),
        }
    }
}

/// Recursive-descent parser over the generator's strict JSON subset.
struct Parser<'a> {
    bytes: &'a [u8],
    pos: usize,
}

impl<'a> Parser<'a> {
    fn new(source: &'a str) -> Self {
        Parser {
            bytes: source.as_bytes(),
            pos: 0,
        }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.bytes.len()
            && matches!(self.bytes[self.pos], b' ' | b'\n' | b'\r' | b'\t')
        {
            self.pos += 1;
        }
    }

    fn expect(&mut self, byte: u8) {
        self.skip_ws();
        assert!(
            self.pos < self.bytes.len() && self.bytes[self.pos] == byte,
            "reference.json: expected {:?} at byte {}",
            byte as char,
            self.pos
        );
        self.pos += 1;
    }

    fn parse_value(&mut self) -> Json {
        self.skip_ws();
        match self.bytes.get(self.pos).copied() {
            Some(b'{') => self.parse_object(),
            Some(b'[') => self.parse_array(),
            Some(b'"') => Json::Str(self.parse_string()),
            Some(b'0'..=b'9') => self.parse_number(),
            other => panic!("reference.json: unexpected {other:?} at byte {}", self.pos),
        }
    }

    fn parse_object(&mut self) -> Json {
        self.expect(b'{');
        let mut members = Vec::new();
        self.skip_ws();
        if self.bytes.get(self.pos) == Some(&b'}') {
            self.pos += 1;
            return Json::Obj(members);
        }
        loop {
            self.skip_ws();
            let key = self.parse_string();
            self.expect(b':');
            let value = self.parse_value();
            members.push((key, value));
            self.skip_ws();
            match self.bytes.get(self.pos) {
                Some(b',') => self.pos += 1,
                Some(b'}') => {
                    self.pos += 1;
                    return Json::Obj(members);
                }
                other => panic!(
                    "reference.json: expected , or }} at byte {}, got {other:?}",
                    self.pos
                ),
            }
        }
    }

    fn parse_array(&mut self) -> Json {
        self.expect(b'[');
        let mut items = Vec::new();
        self.skip_ws();
        if self.bytes.get(self.pos) == Some(&b']') {
            self.pos += 1;
            return Json::Arr(items);
        }
        loop {
            items.push(self.parse_value());
            self.skip_ws();
            match self.bytes.get(self.pos) {
                Some(b',') => self.pos += 1,
                Some(b']') => {
                    self.pos += 1;
                    return Json::Arr(items);
                }
                other => panic!(
                    "reference.json: expected , or ] at byte {}, got {other:?}",
                    self.pos
                ),
            }
        }
    }

    fn parse_string(&mut self) -> String {
        self.expect(b'"');
        let start = self.pos;
        while self.pos < self.bytes.len() && self.bytes[self.pos] != b'"' {
            assert_ne!(
                self.bytes[self.pos], b'\\',
                "reference.json: escape sequences are not emitted by the generator"
            );
            self.pos += 1;
        }
        assert!(
            self.pos < self.bytes.len(),
            "reference.json: unterminated string at byte {start}"
        );
        let text = core::str::from_utf8(&self.bytes[start..self.pos])
            .expect("reference.json: string must be UTF-8");
        self.pos += 1;
        text.to_owned()
    }

    fn parse_number(&mut self) -> Json {
        let start = self.pos;
        while self.pos < self.bytes.len() && self.bytes[self.pos].is_ascii_digit() {
            self.pos += 1;
        }
        let text = core::str::from_utf8(&self.bytes[start..self.pos])
            .expect("reference.json: number must be ASCII");
        Json::Num(
            text.parse::<u64>()
                .unwrap_or_else(|e| panic!("reference.json: bad number {text:?}: {e}")),
        )
    }
}

/// Parses the whole committed document.
fn parse_document(source: &str) -> Json {
    let mut parser = Parser::new(source);
    let value = parser.parse_value();
    parser.skip_ws();
    assert_eq!(
        parser.pos,
        source.len(),
        "reference.json: trailing bytes after the document"
    );
    value
}

// ---------------------------------------------------------------------------
// Corpus recipes — mirrored from tools/gen-reference/main.rs
// ---------------------------------------------------------------------------

/// Builds the deterministic input bytes for a corpus kind.
fn build_input(kind: &str, seed: u64, length: usize) -> Vec<u8> {
    match kind {
        "splitmix64" => {
            let mut rng = SplitMix64::new(seed);
            let mut out = vec![0u8; length];
            rng.fill_bytes(&mut out);
            out
        }
        "zeros" => vec![0u8; length],
        "fill-ff" => vec![0xffu8; length],
        "sawtooth" => (0..length).map(|i| ((i * 7 + 13) % 256) as u8).collect(),
        other => panic!("unknown corpus kind {other:?}"),
    }
}

/// Maps the JSON normalization level to the enum.
fn level(value: u64) -> Normalization {
    match value {
        0 => Normalization::Level0,
        1 => Normalization::Level1,
        2 => Normalization::Level2,
        3 => Normalization::Level3,
        other => panic!("reference.json: unknown normalization level {other}"),
    }
}

/// The expected `[offset, length, fingerprint-hex]` triple for one chunk.
fn expected_triple(entry: &Json, name: &str, index: usize) -> (usize, usize, String) {
    let triple = entry.as_arr();
    assert_eq!(
        triple.len(),
        3,
        "reference.json: chunk {index} of {name} is not an [offset, length, hash] triple"
    );
    (
        triple[0].as_num() as usize,
        triple[1].as_num() as usize,
        triple[2].as_str().to_owned(),
    )
}

// ---------------------------------------------------------------------------
// Conformance tests
// ---------------------------------------------------------------------------

#[test]
fn reference_vectors_reproduce_exactly() {
    let vectors = parse_document(REFERENCE_JSON)
        .get("vectors")
        .as_arr()
        .to_vec();
    assert!(vectors.len() >= 8, "corpus shrank below the frozen set");
    for vector in &vectors {
        let name = vector.get("name").as_str().to_owned();
        let input = vector.get("input");
        let kind = input.get("kind").as_str().to_owned();
        let seed = u64::from_str_radix(input.get("seed_hex").as_str(), 16)
            .unwrap_or_else(|e| panic!("reference.json: bad seed in {name}: {e}"));
        let length = input.get("length").as_num() as usize;
        let params = vector.get("params");
        let min = params.get("min_size").as_num() as usize;
        let avg = params.get("avg_size").as_num() as usize;
        let max = params.get("max_size").as_num() as usize;
        let norm = level(params.get("level").as_num());

        let data = build_input(&kind, seed, length);
        let chunks: Vec<Chunk> = FastCdc::with_level(&data, min, avg, max, norm)
            .unwrap_or_else(|e| panic!("reference.json: invalid params in {name}: {e:?}"))
            .collect();

        let expected = vector.get("chunks").as_arr();
        assert_eq!(
            chunks.len(),
            expected.len(),
            "reference.json: {name} chunk count drifted"
        );
        for (index, (chunk, want)) in chunks.iter().zip(expected).enumerate() {
            let (offset, length, hash) = expected_triple(want, &name, index);
            assert_eq!(
                chunk.offset, offset,
                "reference.json: {name} chunk {index} offset"
            );
            assert_eq!(
                chunk.length, length,
                "reference.json: {name} chunk {index} length"
            );
            assert_eq!(
                format!("{:016x}", chunk.hash),
                hash,
                "reference.json: {name} chunk {index} fingerprint"
            );
        }

        // Tiling invariant: the chunks cover the input exactly, in order.
        let mut end = 0usize;
        for chunk in &chunks {
            assert_eq!(
                chunk.offset, end,
                "reference.json: {name} is not contiguous"
            );
            end += chunk.length;
        }
        assert_eq!(
            end, length,
            "reference.json: {name} does not tile its input"
        );
    }
}

#[test]
fn reference_corpus_names_are_unique() {
    let document = parse_document(REFERENCE_JSON);
    let vectors = document.get("vectors").as_arr();
    let names: Vec<&str> = vectors.iter().map(|v| v.get("name").as_str()).collect();
    let mut sorted = names.clone();
    sorted.sort_unstable();
    sorted.dedup();
    assert_eq!(
        names.len(),
        sorted.len(),
        "reference.json: duplicate vector names"
    );
}

#[test]
fn reference_document_shape_is_frozen() {
    let document = parse_document(REFERENCE_JSON);
    assert_eq!(
        document.get("schema").as_str(),
        "pith-cdc.reference.v1",
        "reference.json: schema marker changed"
    );
    assert!(
        document.get("algorithm").as_str().contains("FastCDC"),
        "reference.json: algorithm marker changed"
    );
}
